#project pipeline jenkins project jpro App  // Jenkinsfile Production Pipeline

def COLOR_MAP = [           # Slack notification colors
    'SUCCESS': 'good', 
    'FAILURE': 'danger',
]

pipeline {
    agent any
    

    environment {          
        cluster = "jprostaging"     # ECS cluster name
        service = "jproappprodsvc"  # ECS service name
    }

    stages {

        stage('Deploy to ECS prod') {     # Deploy to ECS staging
            steps {
                withAWS(credentials: 'awscreds', region: 'us-eest-1') {
                    sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
                } 
            }
        }



    }
    post {       # Post-build actions
        always {
            echo 'Slack Notifications.'
            slackSend channel: '#jenkinscicd',
                color: COLOR_MAP[currentBuild.currentResult],
                message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n More info at: ${env.BUILD_URL}"
        }
    }
}